hparams:
  name: "bark_large_lr_ft"


train:
  num_train_steps: 2000000
  batch_size: 12
  max_text_length: 256
  max_history_semantic_length: 256
  max_semantic_length: 768
  semantic_pad: 10000
  text_pad: 129595
  semantic_infer: 129599
  text_offset: 10048
  train_data_folder: '/data4/leishun/text_to_semantic/datasets/train_segment.json'
#  train_data_folder: '/data4/leishun/text_to_semantic/datasets/test_segment.json'
  test_data_folder: '/data4/leishun/text_to_semantic/datasets/test_segment.json'
  grad_accum_every: 1
  lr: 0.003
  wd: 0.01
  max_grad_norm: 0.5
  warmup_steps: 4000
  num_workers: 16
  save_model_every: 10000
  save_results_every: 100
















